### ISSUE TITLE
디자인 및 더미 데이터 수정/ 송가람

### ISSUE THREAD

**Issue by thdrkfka** [Team-BraBu/Green-touch#50]
## Description
> 디자인 및 더미 데이터 수정

## To-Do List
- [ ] todo 1 플랜테리어 및 상품리스트 페이지의 더미용 데이터 분리 작업
- [ ] todo 2 인스타 피드 형식의 플랜테리어 디자인 일부 수정
- [ ] todo 3 인스타 피드 형식의 플랜테리어 북마크 버튼 누를 시, 내 활동 내역에 저장하는 로직 구현

## ETC.
-
